import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

import 'firebase_options.dart'; // generated by: flutterfire configure
import 'screens/onboarding/linkedin_auth_screen.dart';
import 'screens/onboarding/skill_selection_screen.dart';
import 'screens/swipe/swipe_feed_screen.dart';
import 'screens/messages/chat_screen.dart';
import 'services/auth_service.dart';
import 'services/firestore_service.dart';
import 'models/match.dart';

// Handle background push notifications
@pragma('vm:entry-point')
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
}

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);
  runApp(const RecruitableApp());
}

// ─── Router ───────────────────────────────────────────────────────────────────

final _router = GoRouter(
  initialLocation: '/',
  redirect: (context, state) {
    final user = AuthService.instance.currentUser;
    final isAuth = user != null;
    final isOnAuthPath = state.matchedLocation.startsWith('/auth') ||
        state.matchedLocation == '/';

    if (!isAuth && !isOnAuthPath) return '/';
    return null;
  },
  routes: [
    // Splash / landing
    GoRoute(
      path: '/',
      builder: (_, __) => const SplashScreen(),
    ),

    // LinkedIn OAuth WebView
    GoRoute(
      path: '/auth/linkedin',
      builder: (_, __) => const LinkedInAuthScreen(),
    ),

    // Onboarding
    GoRoute(
      path: '/onboarding/skills',
      builder: (_, __) => const SkillSelectionScreen(),
    ),
    GoRoute(
      path: '/onboarding/location',
      builder: (_, __) => const LocationPickerScreen(),
    ),

    // Main swipe feed
    GoRoute(
      path: '/feed',
      builder: (_, __) => const SwipeFeedScreen(),
    ),

    // Matches list
    GoRoute(
      path: '/matches',
      builder: (_, __) => const MatchesScreen(),
    ),

    // Chat
    GoRoute(
      path: '/matches/:matchId/chat',
      builder: (context, state) {
        final matchId = state.pathParameters['matchId']!;
        final match = state.extra as Match;
        return ChatScreen(match: match);
      },
    ),

    // Profile
    GoRoute(
      path: '/profile',
      builder: (_, __) => const ProfileScreen(),
    ),
  ],
);

// ─── App Root ─────────────────────────────────────────────────────────────────

class RecruitableApp extends StatelessWidget {
  const RecruitableApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      title: 'Recruitable Asia',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        useMaterial3: true,
        fontFamily: 'Nunito',
        colorScheme: ColorScheme.fromSeed(
          seedColor: const Color(0xFFE91E63),
          brightness: Brightness.light,
        ),
        scaffoldBackgroundColor: const Color(0xFFF4F6FB),
        appBarTheme: const AppBarTheme(
          backgroundColor: Colors.white,
          surfaceTintColor: Colors.transparent,
          elevation: 0,
          centerTitle: false,
        ),
      ),
      routerConfig: _router,
    );
  }
}

// ─── Splash / Landing Screen ──────────────────────────────────────────────────

class SplashScreen extends StatelessWidget {
  const SplashScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      body: SafeArea(
        child: Padding(
          padding: const EdgeInsets.symmetric(horizontal: 32),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              const SizedBox(height: 64),
              // Logo
              Row(
                children: [
                  Container(
                    width: 44, height: 44,
                    decoration: const BoxDecoration(
                      color: Color(0xFFE91E63),
                      borderRadius: BorderRadius.all(Radius.circular(10)),
                    ),
                    child: const Icon(Icons.extension, color: Colors.white, size: 26),
                  ),
                  const SizedBox(width: 12),
                  const Text(
                    'recruitable',
                    style: TextStyle(fontFamily: 'Nunito', fontWeight: FontWeight.w900, fontSize: 28, color: Color(0xFF212121)),
                  ),
                ],
              ),
              const SizedBox(height: 48),

              // Headline
              const Text(
                'Find your next\ntech role.\nSwipe to match.',
                style: TextStyle(fontFamily: 'Nunito', fontWeight: FontWeight.w900, fontSize: 38, color: Color(0xFF212121), height: 1.15),
              ),
              const SizedBox(height: 16),
              const Text(
                'AI-powered matching for tech talent across Malaysia, Singapore, Australia, Vietnam, Indonesia, and Thailand.',
                style: TextStyle(fontFamily: 'Nunito', fontWeight: FontWeight.w500, fontSize: 15, color: Color(0xFF8A8A9E), height: 1.5),
              ),
              const Spacer(),

              // LinkedIn CTA
              SizedBox(
                width: double.infinity,
                height: 56,
                child: ElevatedButton.icon(
                  onPressed: () => context.go('/auth/linkedin'),
                  icon: const Icon(Icons.link, color: Colors.white),
                  label: const Text(
                    'Continue with LinkedIn',
                    style: TextStyle(fontFamily: 'Nunito', fontWeight: FontWeight.w800, fontSize: 16, color: Colors.white),
                  ),
                  style: ElevatedButton.styleFrom(
                    backgroundColor: const Color(0xFF0077B5), // LinkedIn blue
                    elevation: 0,
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
                  ),
                ),
              ),
              const SizedBox(height: 12),

              // Privacy note
              const Center(
                child: Text(
                  'No phone numbers or emails are shared.\nOnly your specialism and skills.',
                  textAlign: TextAlign.center,
                  style: TextStyle(fontFamily: 'Nunito', fontSize: 11, color: Color(0xFFBDBDBD)),
                ),
              ),
              const SizedBox(height: 32),
            ],
          ),
        ),
      ),
    );
  }
}

// ─── Placeholder screens (implement in Phase 2) ───────────────────────────────

class LocationPickerScreen extends StatefulWidget {
  const LocationPickerScreen({super.key});

  @override
  State<LocationPickerScreen> createState() => _LocationPickerScreenState();
}

class _LocationPickerScreenState extends State<LocationPickerScreen> {
  String? _selected;
  bool _saving = false;

  Future<void> _confirm() async {
    if (_selected == null || _saving) return;
    setState(() => _saving = true);

    final uid = AuthService.instance.currentUser?.uid;
    if (uid == null) return;

    await FirestoreService.instance.updateLocationOnly(uid: uid, location: _selected!);
    if (mounted) context.go('/feed');
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      appBar: AppBar(
        backgroundColor: Colors.white,
        elevation: 0,
        title: const Text(
          'Where are you based?',
          style: TextStyle(fontFamily: 'Nunito', fontWeight: FontWeight.w800, fontSize: 18, color: Color(0xFF212121)),
        ),
      ),
      body: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const Padding(
            padding: EdgeInsets.fromLTRB(24, 8, 24, 20),
            child: Text(
              'We focus on APAC opportunities.\nSelect your base — we\'ll show you local roles first.',
              style: TextStyle(fontFamily: 'Nunito', fontWeight: FontWeight.w500, fontSize: 14, color: Color(0xFF8A8A9E), height: 1.5),
            ),
          ),
          Expanded(
            child: ListView.separated(
              padding: const EdgeInsets.symmetric(horizontal: 24),
              itemCount: AppConfig.apacRegions.length,
              separatorBuilder: (_, __) => const SizedBox(height: 10),
              itemBuilder: (context, i) {
                final region = AppConfig.apacRegions[i];
                final isSelected = _selected == region.code;
                return GestureDetector(
                  onTap: () => setState(() => _selected = region.code),
                  child: AnimatedContainer(
                    duration: const Duration(milliseconds: 180),
                    padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 18),
                    decoration: BoxDecoration(
                      color: isSelected ? const Color(0xFFE91E63) : const Color(0xFFF4F6FB),
                      borderRadius: BorderRadius.circular(16),
                      border: Border.all(
                        color: isSelected ? const Color(0xFFE91E63) : const Color(0xFFE8ECF4),
                        width: isSelected ? 2 : 1,
                      ),
                    ),
                    child: Row(
                      children: [
                        Text(region.flag, style: const TextStyle(fontSize: 28)),
                        const SizedBox(width: 16),
                        Expanded(
                          child: Column(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              Text(
                                region.label,
                                style: TextStyle(
                                  fontFamily: 'Nunito',
                                  fontWeight: FontWeight.w800,
                                  fontSize: 17,
                                  color: isSelected ? Colors.white : const Color(0xFF212121),
                                ),
                              ),
                              Text(
                                region.city,
                                style: TextStyle(
                                  fontFamily: 'Nunito',
                                  fontWeight: FontWeight.w500,
                                  fontSize: 12,
                                  color: isSelected ? Colors.white.withOpacity(0.8) : const Color(0xFF8A8A9E),
                                ),
                              ),
                            ],
                          ),
                        ),
                        if (isSelected)
                          const Icon(Icons.check_circle, color: Colors.white, size: 22),
                      ],
                    ),
                  ),
                );
              },
            ),
          ),

          // "I'm elsewhere" escape hatch — non-APAC users can still sign up
          Padding(
            padding: const EdgeInsets.fromLTRB(24, 12, 24, 8),
            child: GestureDetector(
              onTap: () => setState(() => _selected = 'OTHER'),
              child: AnimatedContainer(
                duration: const Duration(milliseconds: 180),
                padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 14),
                decoration: BoxDecoration(
                  color: _selected == 'OTHER' ? const Color(0xFF212121) : Colors.white,
                  borderRadius: BorderRadius.circular(16),
                  border: Border.all(
                    color: _selected == 'OTHER' ? const Color(0xFF212121) : const Color(0xFFE0E0E0),
                  ),
                ),
                child: Row(
                  children: [
                    const Text('🌍', style: TextStyle(fontSize: 24)),
                    const SizedBox(width: 14),
                    Text(
                      'I\'m based elsewhere',
                      style: TextStyle(
                        fontFamily: 'Nunito',
                        fontWeight: FontWeight.w700,
                        fontSize: 15,
                        color: _selected == 'OTHER' ? Colors.white : const Color(0xFF424242),
                      ),
                    ),
                    const Spacer(),
                    if (_selected == 'OTHER')
                      const Icon(Icons.check_circle, color: Colors.white, size: 22),
                  ],
                ),
              ),
            ),
          ),

          // CTA
          SafeArea(
            child: Padding(
              padding: const EdgeInsets.fromLTRB(24, 8, 24, 24),
              child: SizedBox(
                width: double.infinity,
                height: 52,
                child: ElevatedButton(
                  onPressed: _selected != null && !_saving ? _confirm : null,
                  style: ElevatedButton.styleFrom(
                    backgroundColor: const Color(0xFFE91E63),
                    disabledBackgroundColor: const Color(0xFFE0E0E0),
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(14)),
                    elevation: 0,
                  ),
                  child: _saving
                      ? const SizedBox(width: 22, height: 22, child: CircularProgressIndicator(color: Colors.white, strokeWidth: 2.5))
                      : const Text(
                          'Show me roles',
                          style: TextStyle(fontFamily: 'Nunito', fontWeight: FontWeight.w800, fontSize: 16, color: Colors.white),
                        ),
                ),
              ),
            ),
          ),
        ],
      ),
    );
  }
}

class MatchesScreen extends StatelessWidget {
  const MatchesScreen({super.key});

  @override
  Widget build(BuildContext context) {
    final uid = AuthService.instance.currentUser?.uid ?? '';
    return Scaffold(
      appBar: AppBar(title: const Text('My Matches')),
      body: StreamBuilder(
        stream: FirestoreService.instance.watchMatches(uid),
        builder: (context, snapshot) {
          final matches = snapshot.data ?? <Match>[];
          if (matches.isEmpty) {
            return const Center(
              child: Text('No matches yet.\nKeep swiping!', textAlign: TextAlign.center,
                  style: TextStyle(fontFamily: 'Nunito', fontSize: 16, color: Color(0xFF8A8A9E))),
            );
          }
          return ListView.builder(
            padding: const EdgeInsets.all(16),
            itemCount: matches.length,
            itemBuilder: (context, i) {
              final m = matches[i];
              return ListTile(
                leading: CircleAvatar(
                  backgroundColor: const Color(0xFFE91E63),
                  child: Text(m.company[0], style: const TextStyle(color: Colors.white, fontFamily: 'Nunito', fontWeight: FontWeight.w800)),
                ),
                title: Text(m.company, style: const TextStyle(fontFamily: 'Nunito', fontWeight: FontWeight.w700)),
                subtitle: Text(m.jobTitle, style: const TextStyle(fontFamily: 'Nunito', fontSize: 12)),
                trailing: Column(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    Text('${m.matchScore}%', style: const TextStyle(fontFamily: 'Nunito', fontWeight: FontWeight.w900, color: Color(0xFFE91E63))),
                    if (m.hasUnreadMessages)
                      Container(width: 8, height: 8, decoration: const BoxDecoration(color: Color(0xFFE91E63), shape: BoxShape.circle)),
                  ],
                ),
                onTap: () => context.go('/matches/${m.id}/chat', extra: m),
              );
            },
          );
        },
      ),
    );
  }
}

class ProfileScreen extends StatelessWidget {
  const ProfileScreen({super.key});

  @override
  Widget build(BuildContext context) {
    final uid = AuthService.instance.currentUser?.uid ?? '';
    return Scaffold(
      appBar: AppBar(title: const Text('My Profile')),
      body: StreamBuilder(
        stream: FirestoreService.instance.watchUser(uid),
        builder: (context, snapshot) {
          final profile = snapshot.data;
          if (profile == null) return const Center(child: CircularProgressIndicator(color: Color(0xFFE91E63)));
          return Center(child: Text('Profile: ${profile.displayName}'));
        },
      ),
    );
  }
}
